### ISSUE TITLE
Showing next month?

### ISSUE THREAD

**Issue by martin-braun** [jrvarma/icalcli#10]
Love `m --monday --military`, but I would love it more to have a look at the next month (as well).

**Comment by jrvarma** [comment]
Please see whether `w -n 9 "1 April 2024"` gives you the desired view of April and May 2024. In that case, the `m` command can be changed to accept a `-n` argument for the number of months, and then the code can automatically run a `w` command with the appropriate start date and week count.

Alternatively, `m -n 2` run in April can be designed to produce the same output as `m` followed by `m May`

**Comment by jrvarma** [comment]
Version 1.0.5 adds a `cal5w` command to display current week and two past and two future weeks. So in middle of month, this will be almost same as month view. Later in the month, it will give part of this month and part of next month. Early in the month, it will give part of this month and part of previous month. 

This command has a `-n` option to increase the number of weeks.

**Comment by martin-braun** [comment]
Hi @jrvarma `w -n` looks almost what I would want. I think the `cal5w` command isn't necessary, because it's just like `w -n` with the ability to also look into the past.

My suggestion would be to extend `w` with another flag for the weeks into the past instead. Looking at the result of `w -n` and `cal5w -n` I think the perfect solution would be something like `w -n 4 -N 1` for me (`-N` for weeks into the past), so that I can see the last week and look ahead 4 weeks in advance.

Please let me know what you think and thanks for the good work. 🙏
