### ISSUE TITLE
Do not hide stacktrace by default

### ISSUE THREAD

**Issue by drzraf** [jrvarma/icalcli#4]
`$ icalcli`

**Actual**
```
'NoneType' object has no attribute 'upper'
```
(I've to add `print` statement to find the bug)

**Expected**: The full stacktrace

**Comment by jrvarma** [comment]
This is a feature inherited from gcalcli which prevents the script from exiting with a stack trace for every error. Catching all errors ensures that if one command fails, the script continues running to process new commands.

**Comment by jrvarma** [comment]
One possibility is to have a command line option that enables abort with stack trace. This way in normal use, the code continues to run after an error, but debugging is still possible by setting this option.

**Comment by jrvarma** [comment]
Command line `--stack_trace` enables a stack trace in version 0.9.9
