### ISSUE TITLE
Open more than one ics in read-only mode?

### ISSUE THREAD

**Issue by martin-braun** [jrvarma/icalcli#9]
I love the tool, but I try to manage multiple calendars with it. Adding or editing can easily be done by having multiple configuration files and building appropriate aliases for it, but now I want to get an overview of all events in a single week or month view.

It would be nice, if the configuration could accept an array of ics files and consequently open those within one instance in read-only mode.

**Comment by jrvarma** [comment]
The best way to do this is probably by modifying `file_backend/ics_interface.py` to loop over multiple `ics` files. Perhaps, we should try to fix duplicate `uids` across files by prefixing each `uid` with a filename. I will look into this.

**Comment by jrvarma** [comment]
Done in version 1.0.5

**Comment by martin-braun** [comment]
@jrvarma Wow just wow, this is exactly what I wanted. Now I can have a great overview of all my ICS files, maintaining proper context in each of them. To give some insights. My girlfriend and I share ICS files via Syncthing, and we subscribe each others calendar, but I also have a private calendar. With this merge feature I can finally see all our events with one single command. Good job.

One final suggestion though. Could you please output "Calendar backend interface is readonly" to stderr, so that I could suppress the message. Right now it's sent to stdout. I bypass this by removing the first line from the output, but it's less optimal for obvious reasons.
